### ISSUE TITLE
Error: Argument list too long

### ISSUE THREAD

**Issue by grasshoffm** [caleblareau/maegatk#4]
Hi. I ran maegatk for 4 samples. For three I got this error:

```
/bin/sh: /usr/bin/ls: Argument list too long
ERROR: Could not import any samples from the user specification; check flags, logs and input configuration; QUITTING
```
The tool split the bam file as it should, but did not create any log files or folders.

I tried maegtk and maegatk. Both failed with the same error. When I tried mgatk, it worked fine.

**Comment by caleblareau** [comment]
Can you specify the commands that you used on mgatk versus maegatk?

**Comment by grasshoffm** [comment]
I pretty much used the same commands, see below. 

```
maegatk bcall \
       --ncores $NCORES \
       --snake-stdout \
       --min-barcode-reads 3 \
       --nsamples 1024 \
       --barcode-tag "CB" \
       --umi-barcode "UB" \
       --input $bams_use \
       --output $output_path \
       --alignment-quality 30 \
       --mito-genome "gene_annotation/refdata-gex-GRCh38-2020-A/fasta/genome.fa"

mgatk tenx \
       --ncores $NCORES \
       --snake-stdout \
       --nsamples 1024 \
       --barcodes $cells_use \
       --barcode-tag "CB" \
       --umi-barcode "UB" \
       --input $bams_use \
       --output $OUTPUT$sample_use \
       --alignment-quality 30 \
       --mito-genome gene_annotation/refdata-gex-GRCh38-2020-A/fasta/genome.fa
```

**Comment by caleblareau** [comment]
Right so in maegatk, each cell get split into its own .bam file because that's how I could get the consensus read collapse to work. The mgatk `tenx` mode is written where it doesn't produce that number of bams (it only produces as many parallel cores as you let it process). The other difference that I see is that you subset which barcodes to use in the mgatk call but not the maegatk call, so you are probably processing many barcodes that aren't real cells.

**Comment by grasshoffm** [comment]
I ran maegatk again with the --barcodes parameter set. Now, it worked.

**Comment by dstyaaaaaa** [comment]
Hello, I also encountered the same problem, but I set the parameters of -b and -bt.
![image](https://github.com/user-attachments/assets/ac4d62f1-65fd-4851-b813-5aa454f9740f)
![image](https://github.com/user-attachments/assets/89521cf1-29e1-4e8d-9af4-6aa370e671fb)
Since it's not 10x data, I can't run mgatk in 'tenx' mode. I tried to run mgatk bcall but that too failed. Unlike the maegatk run,mgatk runs without error, but produces an unexpected output file:
![image](https://github.com/user-attachments/assets/b88984aa-71d7-4c3e-9390-d6baa69a8861)
![image](https://github.com/user-attachments/assets/10544092-7ab8-411d-8e2b-c012c61181c4)
![image](https://github.com/user-attachments/assets/1e6ab1bc-e22d-4e17-9ab6-8e2bf05990d1)
![image](https://github.com/user-attachments/assets/8d50cbb4-e3cc-431f-af4a-d966c72f12d1)
I don't know what caused it.
